### ISSUE TITLE
How to access the cache globally?

### ISSUE THREAD

**Issue by ghost** [Jakobud/vscode-cache#1]
Hi @Jakobud,

First of all, thank you for this awesome library, which has helped me quite a bit in developing my VS Code extension.

Quick question: Is there a way I can access the cache globally? For example, I would like to access it in my hover provider, to provide dynamic hover content. Would this be possible with your library?

All the best,
Ardit

**Comment by Jakobud** [comment]
I believe that the individual caches for an extension have to be made using that extensions `extensionContext` object as shown in the documentation. I believe that is a requirement of the `globalState` object if you look into the VSCode extension development documentation.

But it is all JavaScript. Maybe just doing this would work;

```
myCustomExtensionCache = new Cache(extensionContext);
```

without using `let` or `var` or `const`, a variable would generally be available "globally" but I don't know if that works in the VSCode environment or not. Never tried.

**Comment by ghost** [comment]
I am not sure if your suggestion would work (I have not tried it - I assume it wouldn't work because of Typescript), but this is how I managed to access the cache globally:

In the root directory of the extension, I created two files: `global.d.ts` and `global-declaration.js`:

`global.d.ts`
```typescript
declare var extensionCache: any;
```

`global-declaration.js`
```javascript
extensionCache = null;
```

Then, in `src/extension.ts` I imported `global-declaration.js`:

```typescript
const Cache = require('vscode-cache');
import '../global-declaration.js';

...

export function activate(context: vscode.ExtensionContext) {
    extensionCache = new Cache(context);
    // Now you can use the cache globally
}
```

It is not a pretty solution obviously, but it worked for my purposes   ¯\_(ツ)_/¯

Thanks for your help!

**Comment by Jakobud** [comment]
Glad you figured it out!
